line_follower:
  ros__parameters:

    # ---------- BLACK LINE ----------

    black_threshold: 75

    contour_min_area: 2500

    min_tape_width: 70
    max_tape_width: 600

    width_center_bonus: 0.5


    # ---------- RED STOP ----------

    red_low_h: 0
    red_high_h: 10

    red2_low_h: 170
    red2_high_h: 180

    red_s_min: 100
    red_v_min: 100

    stop_pixel_thresh: 2500

    red_min_width: 120
    red_max_width: 700

    red_min_area: 2500

    stop_time: 5.0


    # ---------- ROI ----------

    line_roi_height: 0.55
    red_roi_height: 0.20


    # ---------- STEERING ----------

    kp: 0.25

    servo_center: 90

    servo_min: 0
    servo_max: 180


    # ---------- SPEED ----------

    speed_fast: 120
    speed_turn: 90

    # black validation

    min_black_pixels: 7000

    min_fill_ratio: 0.24


    max_black_percent: 0.65
    red_ignore_time: 2.5

    line_loss_delay: 1.0

    reverse_timeout: 30.0
    reverse_step_time: 2.5
